// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx2vAR7NMA2x5w7xnlsXA5p1jZYMdprcM',
    appId: '1:691009956952:web:5d5cb120f0367a44126e2d',
    messagingSenderId: '691009956952',
    projectId: 'community-boating-center',
    authDomain: 'community-boating-center.firebaseapp.com',
    storageBucket: 'community-boating-center.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0wACHeMc11qPlzO_Cb2QkzrCkmdDRdXk',
    appId: '1:691009956952:android:92927dfb9e6c88ef126e2d',
    messagingSenderId: '691009956952',
    projectId: 'community-boating-center',
    storageBucket: 'community-boating-center.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ZfzhKTRiZAPY2hAvH8MCEFhOh5t_BCs',
    appId: '1:691009956952:ios:477c9d65bd116af5126e2d',
    messagingSenderId: '691009956952',
    projectId: 'community-boating-center',
    storageBucket: 'community-boating-center.appspot.com',
    iosClientId: '691009956952-n1cgn72e5gl5lf6kpiigrffi4nbv0je7.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3ZfzhKTRiZAPY2hAvH8MCEFhOh5t_BCs',
    appId: '1:691009956952:ios:477c9d65bd116af5126e2d',
    messagingSenderId: '691009956952',
    projectId: 'community-boating-center',
    storageBucket: 'community-boating-center.appspot.com',
    iosClientId: '691009956952-n1cgn72e5gl5lf6kpiigrffi4nbv0je7.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx2vAR7NMA2x5w7xnlsXA5p1jZYMdprcM',
    appId: '1:691009956952:web:fdc6c898f99ac6b2126e2d',
    messagingSenderId: '691009956952',
    projectId: 'community-boating-center',
    authDomain: 'community-boating-center.firebaseapp.com',
    storageBucket: 'community-boating-center.appspot.com',
  );
}
